name: Upload Python Package

on:
  push: 
    branches: ['main']
  workflow_dispatch: 

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup docker
        uses: docker/setup-docker-action@e43656e248c0bd0647d3f5c195d116aacf6fcaf4

      - name: generate tag
        id: image_tag
        run: echo "value=${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: build container image
        run: |
          docker build -t ayobamiblackforce/guessing-game-staging:${{ steps.image_tag.outputs.value }} .

      - name: build container image
        run: |
          docker run -d --name guessing-game ayobamiblackforce/guessing-game-staging:${{ steps.image_tag.outputs.value }}

      - name: check status
        run: |
          docker images
          docker ps
          
      - name: image scanning
        uses: snowcittysolutions/scout-action-dev@eb15de5b9247f4800f2c9ac4896bbddeff4defb5
        with:
          command: cves, quickview
          only-severities: critical, high
          exit-on: true
          sarif-file: spdx
          output: scout-report.spdx
          dockerhub-user: ayobamiblackforce
          dockerhub-password: ${{ vars.DOCKERHUB_TOKEN }}

      - name: OWASP ZAP Full Scan
        #uses: zaproxy/action-baseline@v0.10.0
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:8501'
          fail_action: true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report
          path: report_html.html

          
                  # - name: push to repo
                  #   run: |
                  #     echo ${{ vars.DOCKERHUB_TOKEN }} | docker login -u ayobamiblackforce --password-stdin
                  #     docker push ayobamiblackforce/guessing-game-staging:${{ steps.image_tag.outputs.value }}
