name: Upload Python Package

on:
  push: 
    branches: ['main']
  workflow_dispatch: 

# permissions:
#   contents: read

jobs:
  SAST-scan_SONARQUBE:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - uses: SonarSource/sonarqube-scan-action@v7.0.0
        with:
          args: >
            -Dsonar.qualitygate.wait=false
            -Dsonar.projectKey=ayobamiblackforce-100_guessing-game-ayo 
            -Dsonar.organization=ayobamiblackforce-100
        env:
          SONAR_TOKEN: ${{ vars.SONARCLOUD }}            


  SCA-scan_PIP-AUDIT:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
          
      - name: Run dependency scan
        run: |
          pip install pip-audit
          pip-audit -r app/requirements.txt --output sca-report.txt
          
      - name: Display sca-report
        run: |
          echo "$(cat sca-report.txt)"
          




# jobs:
#   release-build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: setup docker
#         uses: docker/setup-docker-action@e43656e248c0bd0647d3f5c195d116aacf6fcaf4

#       - name: generate tag
#         id: image_tag
#         run: echo "value=${{ github.sha }}" >> "$GITHUB_OUTPUT"

#       - name: build container image
#         run: |
#           docker build -t ayobamiblackforce/guessing-game-staging:${{ steps.image_tag.outputs.value }} .

#       - name: build container image
#         run: |
#           docker run -d --name guessing-game ayobamiblackforce/guessing-game-staging:${{ steps.image_tag.outputs.value }}

#       - name: get container ip
#         id: con_ip
#         run: |
#           echo "value=$(docker exec guessing-game hostname -i)" >> "$GITHUB_OUTPUT"

#       - name: check status
#         run: |
#           docker ps
#           echo ${{ steps.con_ip.outputs.value }}
          
#       - name: image scanning
#         uses: snowcittysolutions/scout-action-dev@eb15de5b9247f4800f2c9ac4896bbddeff4defb5
#         with:
#           command: cves, quickview
#           only-severities: critical, high
#           exit-on: vulnerability
#           sarif-file: spdx
#           output: scout-report.spdx
#           dockerhub-user: ayobamiblackforce
#           dockerhub-password: ${{ vars.DOCKERHUB_TOKEN }}

#       - name: OWASP ZAP Full Scan
#         #uses: zaproxy/action-baseline@v0.10.0
#         uses: zaproxy/action-full-scan@v0.8.0
#         continue-on-error: true
#         with:
#           target: 'http://${{ steps.con_ip.outputs.value }}:8501'     

#       - name: check generated files
#         run: ls

#       # - name: OWASP ZAP Full Scan
#       #   run: |
#       #     docker run -v /home/runner/work/guessing-game-ayo/guessing-game-ayo:/zap/wrk/:rw --network=host \
#       #     -e ZAP_AUTH_HEADER -e ZAP_AUTH_HEADER_VALUE -e ZAP_AUTH_HEADER_SITE -t ghcr.io/zaproxy/zaproxy:stable \
#       #     zap-full-scan.py -t http://${{ steps.con_ip.outputs.value }}:8501 -J report_json.json -w report_md.md -r report_html.html || true

#       - name: Upload ZAP Report
#         uses: actions/upload-artifact@v4
#         if: always()
#         with:
#           name: zap-report.json
#           path: report_json.json

#       - name: Upload scout Report
#         uses: actions/upload-artifact@v4
#         if: always()
#         with:
#           name: scout-report.spdx
#           path: spdx

#       - name: check json file content
#         run: |
#           echo $(python - c "
#           import json

#           with open('report_json.json', 'r') as f:
#               data = json.load(f)          
#           print(data.keys())
#           ")

#       - name: check spdx content
#         run: |
#           echo $(python - c "
#           import json

#           with open('spdx', 'r') as f:
#               data = json.load(f)          
#           print(data.keys())
#           ")
          
#       - name: check spdx content in read mode
#         run: |
#           echo $(python - c "
#           import json

#           with open('report_json.json', 'r') as f:
#               data = f.read()     
#           print(data)
#           ")

#       # - name: push to repo
#       #   run: |
#       #     echo ${{ vars.DOCKERHUB_TOKEN }} | docker login -u ayobamiblackforce --password-stdin
#       #     docker push ayobamiblackforce/guessing-game-staging:${{ steps.image_tag.outputs.value }}

#       # cmd_options: '-z "-config globalalertfilter=High"'
          

